/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.8.0 indecipherable-ferman
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClearFirmwareErrorResponse,
  CreateFirmwareRequest,
  Firmware,
  FirmwareStats,
  FirmwareUsageResponse,
  ListFirmwareResponse,
  Status,
  UpdateFirmwareRequest,
} from '../models';
import {
    ClearFirmwareErrorResponseFromJSON,
    ClearFirmwareErrorResponseToJSON,
    CreateFirmwareRequestFromJSON,
    CreateFirmwareRequestToJSON,
    FirmwareFromJSON,
    FirmwareToJSON,
    FirmwareStatsFromJSON,
    FirmwareStatsToJSON,
    FirmwareUsageResponseFromJSON,
    FirmwareUsageResponseToJSON,
    ListFirmwareResponseFromJSON,
    ListFirmwareResponseToJSON,
    StatusFromJSON,
    StatusToJSON,
    UpdateFirmwareRequestFromJSON,
    UpdateFirmwareRequestToJSON,
} from '../models';

export interface ClearFirmwareErrorRequest {
    collectionId: string;
    deviceId: string;
}

export interface CreateFirmwareOperationRequest {
    collectionId: string;
    body: CreateFirmwareRequest;
}

export interface DeleteFirmwareRequest {
    collectionId: string;
    imageId: string;
}

export interface FirmwareUsageRequest {
    collectionId: string;
    imageId: string;
}

export interface ListFirmwareRequest {
    collectionId: string;
}

export interface RetrieveFirmwareRequest {
    collectionId: string;
    imageId: string;
}

export interface RetrieveFirmwareStatsRequest {
    collectionId: string;
    imageId: string;
}

export interface UpdateFirmwareOperationRequest {
    existingCollectionId: string;
    imageId: string;
    body: UpdateFirmwareRequest;
}

/**
 * 
 */
export class FotaApi extends runtime.BaseAPI {

    /**
     * Clear FOTA error
     */
    async clearFirmwareErrorRaw(requestParameters: ClearFirmwareErrorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClearFirmwareErrorResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling clearFirmwareError.');
        }

        if (requestParameters.deviceId === null || requestParameters.deviceId === undefined) {
            throw new runtime.RequiredError('deviceId','Required parameter requestParameters.deviceId was null or undefined when calling clearFirmwareError.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/devices/{deviceId}/fwerror`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"deviceId"}}`, encodeURIComponent(String(requestParameters.deviceId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClearFirmwareErrorResponseFromJSON(jsonValue));
    }

    /**
     * Clear FOTA error
     */
    async clearFirmwareError(requestParameters: ClearFirmwareErrorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClearFirmwareErrorResponse> {
        const response = await this.clearFirmwareErrorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Firmware images must have unique version numbers and have an unique checksum. The checksum is calculated when the firmware image is uploaded.
     * Create firmware
     */
    async createFirmwareRaw(requestParameters: CreateFirmwareOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Firmware>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling createFirmware.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createFirmware.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/firmware`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFirmwareRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FirmwareFromJSON(jsonValue));
    }

    /**
     * Firmware images must have unique version numbers and have an unique checksum. The checksum is calculated when the firmware image is uploaded.
     * Create firmware
     */
    async createFirmware(requestParameters: CreateFirmwareOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Firmware> {
        const response = await this.createFirmwareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete firmware
     */
    async deleteFirmwareRaw(requestParameters: DeleteFirmwareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Firmware>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling deleteFirmware.');
        }

        if (requestParameters.imageId === null || requestParameters.imageId === undefined) {
            throw new runtime.RequiredError('imageId','Required parameter requestParameters.imageId was null or undefined when calling deleteFirmware.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/firmware/{imageId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters.imageId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FirmwareFromJSON(jsonValue));
    }

    /**
     * Delete firmware
     */
    async deleteFirmware(requestParameters: DeleteFirmwareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Firmware> {
        const response = await this.deleteFirmwareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Firmware usage
     */
    async firmwareUsageRaw(requestParameters: FirmwareUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FirmwareUsageResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling firmwareUsage.');
        }

        if (requestParameters.imageId === null || requestParameters.imageId === undefined) {
            throw new runtime.RequiredError('imageId','Required parameter requestParameters.imageId was null or undefined when calling firmwareUsage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/firmware/{imageId}/usage`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters.imageId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FirmwareUsageResponseFromJSON(jsonValue));
    }

    /**
     * Firmware usage
     */
    async firmwareUsage(requestParameters: FirmwareUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FirmwareUsageResponse> {
        const response = await this.firmwareUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List firmware
     */
    async listFirmwareRaw(requestParameters: ListFirmwareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFirmwareResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling listFirmware.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/firmware`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFirmwareResponseFromJSON(jsonValue));
    }

    /**
     * List firmware
     */
    async listFirmware(requestParameters: ListFirmwareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFirmwareResponse> {
        const response = await this.listFirmwareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve firmware
     */
    async retrieveFirmwareRaw(requestParameters: RetrieveFirmwareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Firmware>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling retrieveFirmware.');
        }

        if (requestParameters.imageId === null || requestParameters.imageId === undefined) {
            throw new runtime.RequiredError('imageId','Required parameter requestParameters.imageId was null or undefined when calling retrieveFirmware.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/firmware/{imageId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters.imageId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FirmwareFromJSON(jsonValue));
    }

    /**
     * Retrieve firmware
     */
    async retrieveFirmware(requestParameters: RetrieveFirmwareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Firmware> {
        const response = await this.retrieveFirmwareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve firmware statistics
     */
    async retrieveFirmwareStatsRaw(requestParameters: RetrieveFirmwareStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FirmwareStats>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling retrieveFirmwareStats.');
        }

        if (requestParameters.imageId === null || requestParameters.imageId === undefined) {
            throw new runtime.RequiredError('imageId','Required parameter requestParameters.imageId was null or undefined when calling retrieveFirmwareStats.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/firmware/{imageId}/stats`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters.imageId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FirmwareStatsFromJSON(jsonValue));
    }

    /**
     * Retrieve firmware statistics
     */
    async retrieveFirmwareStats(requestParameters: RetrieveFirmwareStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FirmwareStats> {
        const response = await this.retrieveFirmwareStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Only the version and tags fields can be updated. The other fields will be ignored.
     * Update firmware
     */
    async updateFirmwareRaw(requestParameters: UpdateFirmwareOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Firmware>> {
        if (requestParameters.existingCollectionId === null || requestParameters.existingCollectionId === undefined) {
            throw new runtime.RequiredError('existingCollectionId','Required parameter requestParameters.existingCollectionId was null or undefined when calling updateFirmware.');
        }

        if (requestParameters.imageId === null || requestParameters.imageId === undefined) {
            throw new runtime.RequiredError('imageId','Required parameter requestParameters.imageId was null or undefined when calling updateFirmware.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling updateFirmware.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{existingCollectionId}/firmware/{imageId}`.replace(`{${"existingCollectionId"}}`, encodeURIComponent(String(requestParameters.existingCollectionId))).replace(`{${"imageId"}}`, encodeURIComponent(String(requestParameters.imageId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFirmwareRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FirmwareFromJSON(jsonValue));
    }

    /**
     * Only the version and tags fields can be updated. The other fields will be ignored.
     * Update firmware
     */
    async updateFirmware(requestParameters: UpdateFirmwareOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Firmware> {
        const response = await this.updateFirmwareRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
