/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.1 busy-janay
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Gateway,
    GatewayFromJSON,
    GatewayToJSON,
    GatewayCertificateResponse,
    GatewayCertificateResponseFromJSON,
    GatewayCertificateResponseToJSON,
    InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    ListGatewayResponse,
    ListGatewayResponseFromJSON,
    ListGatewayResponseToJSON,
    Status,
    StatusFromJSON,
    StatusToJSON,
} from '../models';

export interface CreateGatewayRequest {
    collectionId: string;
    body: InlineObject;
}

export interface DeleteGatewayRequest {
    collectionId: string;
    gatewayId: string;
}

export interface GatewayCertificatesRequest {
    collectionId: string;
    gatewayId: string;
}

export interface ListGatewaysRequest {
    collectionId: string;
}

export interface RetrieveGatewayRequest {
    collectionId: string;
    gatewayId: string;
}

export interface UpdateGatewayRequest {
    existingCollectionId: string;
    gatewayId: string;
    body: InlineObject1;
}

/**
 * 
 */
export class GatewaysApi extends runtime.BaseAPI {

    /**
     * Create a new gateway.
     * Create gateway
     */
    async createGatewayRaw(requestParameters: CreateGatewayRequest): Promise<runtime.ApiResponse<Gateway>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling createGateway.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createGateway.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/gateways`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObjectToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayFromJSON(jsonValue));
    }

    /**
     * Create a new gateway.
     * Create gateway
     */
    async createGateway(requestParameters: CreateGatewayRequest): Promise<Gateway> {
        const response = await this.createGatewayRaw(requestParameters);
        return await response.value();
    }

    /**
     * Remove a gateway from Span.
     * Delete gateway
     */
    async deleteGatewayRaw(requestParameters: DeleteGatewayRequest): Promise<runtime.ApiResponse<Gateway>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling deleteGateway.');
        }

        if (requestParameters.gatewayId === null || requestParameters.gatewayId === undefined) {
            throw new runtime.RequiredError('gatewayId','Required parameter requestParameters.gatewayId was null or undefined when calling deleteGateway.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/gateways/{gatewayId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"gatewayId"}}`, encodeURIComponent(String(requestParameters.gatewayId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayFromJSON(jsonValue));
    }

    /**
     * Remove a gateway from Span.
     * Delete gateway
     */
    async deleteGateway(requestParameters: DeleteGatewayRequest): Promise<Gateway> {
        const response = await this.deleteGatewayRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get issued certificate(s) for gateway
     */
    async gatewayCertificatesRaw(requestParameters: GatewayCertificatesRequest): Promise<runtime.ApiResponse<GatewayCertificateResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling gatewayCertificates.');
        }

        if (requestParameters.gatewayId === null || requestParameters.gatewayId === undefined) {
            throw new runtime.RequiredError('gatewayId','Required parameter requestParameters.gatewayId was null or undefined when calling gatewayCertificates.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/gateways/{gatewayId}/certs`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"gatewayId"}}`, encodeURIComponent(String(requestParameters.gatewayId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayCertificateResponseFromJSON(jsonValue));
    }

    /**
     * Get issued certificate(s) for gateway
     */
    async gatewayCertificates(requestParameters: GatewayCertificatesRequest): Promise<GatewayCertificateResponse> {
        const response = await this.gatewayCertificatesRaw(requestParameters);
        return await response.value();
    }

    /**
     * List the user\'s gatways, including built-in gateways.
     * List gateways
     */
    async listGatewaysRaw(requestParameters: ListGatewaysRequest): Promise<runtime.ApiResponse<ListGatewayResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling listGateways.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/gateways`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ListGatewayResponseFromJSON(jsonValue));
    }

    /**
     * List the user\'s gatways, including built-in gateways.
     * List gateways
     */
    async listGateways(requestParameters: ListGatewaysRequest): Promise<ListGatewayResponse> {
        const response = await this.listGatewaysRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get gateway information
     * Retrieve gateway
     */
    async retrieveGatewayRaw(requestParameters: RetrieveGatewayRequest): Promise<runtime.ApiResponse<Gateway>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling retrieveGateway.');
        }

        if (requestParameters.gatewayId === null || requestParameters.gatewayId === undefined) {
            throw new runtime.RequiredError('gatewayId','Required parameter requestParameters.gatewayId was null or undefined when calling retrieveGateway.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/gateways/{gatewayId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"gatewayId"}}`, encodeURIComponent(String(requestParameters.gatewayId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayFromJSON(jsonValue));
    }

    /**
     * Get gateway information
     * Retrieve gateway
     */
    async retrieveGateway(requestParameters: RetrieveGatewayRequest): Promise<Gateway> {
        const response = await this.retrieveGatewayRaw(requestParameters);
        return await response.value();
    }

    /**
     * Update a gateway in Span
     * Update gateway
     */
    async updateGatewayRaw(requestParameters: UpdateGatewayRequest): Promise<runtime.ApiResponse<Gateway>> {
        if (requestParameters.existingCollectionId === null || requestParameters.existingCollectionId === undefined) {
            throw new runtime.RequiredError('existingCollectionId','Required parameter requestParameters.existingCollectionId was null or undefined when calling updateGateway.');
        }

        if (requestParameters.gatewayId === null || requestParameters.gatewayId === undefined) {
            throw new runtime.RequiredError('gatewayId','Required parameter requestParameters.gatewayId was null or undefined when calling updateGateway.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling updateGateway.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{existingCollectionId}/gateways/{gatewayId}`.replace(`{${"existingCollectionId"}}`, encodeURIComponent(String(requestParameters.existingCollectionId))).replace(`{${"gatewayId"}}`, encodeURIComponent(String(requestParameters.gatewayId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject1ToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GatewayFromJSON(jsonValue));
    }

    /**
     * Update a gateway in Span
     * Update gateway
     */
    async updateGateway(requestParameters: UpdateGatewayRequest): Promise<Gateway> {
        const response = await this.updateGatewayRaw(requestParameters);
        return await response.value();
    }

}
