/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.1 humorous-jaron
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateOutputBody,
  ListOutputResponse,
  Output,
  OutputLogResponse,
  OutputStats,
  OutputStatusResponse,
  RpcStatus,
  UpdateOutputBody,
} from '../models';
import {
    CreateOutputBodyFromJSON,
    CreateOutputBodyToJSON,
    ListOutputResponseFromJSON,
    ListOutputResponseToJSON,
    OutputFromJSON,
    OutputToJSON,
    OutputLogResponseFromJSON,
    OutputLogResponseToJSON,
    OutputStatsFromJSON,
    OutputStatsToJSON,
    OutputStatusResponseFromJSON,
    OutputStatusResponseToJSON,
    RpcStatusFromJSON,
    RpcStatusToJSON,
    UpdateOutputBodyFromJSON,
    UpdateOutputBodyToJSON,
} from '../models';

export interface CreateOutputRequest {
    collectionId: string;
    body: CreateOutputBody;
}

export interface DeleteOutputRequest {
    collectionId: string;
    outputId: string;
}

export interface ListOutputsRequest {
    collectionId: string;
}

export interface LogsRequest {
    collectionId: string;
    outputId: string;
}

export interface RetrieveOutputRequest {
    collectionId: string;
    outputId: string;
}

export interface RetrieveOutputStatsRequest {
    collectionId: string;
    outputId: string;
}

export interface StatusRequest {
    collectionId: string;
    outputId: string;
}

export interface UpdateOutputRequest {
    existingCollectionId: string;
    outputId: string;
    body: UpdateOutputBody;
}

/**
 * 
 */
export class OutputsApi extends runtime.BaseAPI {

    /**
     * Create output
     */
    async createOutputRaw(requestParameters: CreateOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Output>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling createOutput.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling createOutput.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/outputs`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOutputBodyToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutputFromJSON(jsonValue));
    }

    /**
     * Create output
     */
    async createOutput(requestParameters: CreateOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Output> {
        const response = await this.createOutputRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete output
     */
    async deleteOutputRaw(requestParameters: DeleteOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Output>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling deleteOutput.');
        }

        if (requestParameters.outputId === null || requestParameters.outputId === undefined) {
            throw new runtime.RequiredError('outputId','Required parameter requestParameters.outputId was null or undefined when calling deleteOutput.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/outputs/{outputId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"outputId"}}`, encodeURIComponent(String(requestParameters.outputId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutputFromJSON(jsonValue));
    }

    /**
     * Delete output
     */
    async deleteOutput(requestParameters: DeleteOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Output> {
        const response = await this.deleteOutputRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List outputs
     */
    async listOutputsRaw(requestParameters: ListOutputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListOutputResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling listOutputs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/outputs`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListOutputResponseFromJSON(jsonValue));
    }

    /**
     * List outputs
     */
    async listOutputs(requestParameters: ListOutputsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListOutputResponse> {
        const response = await this.listOutputsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Output logs
     */
    async logsRaw(requestParameters: LogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutputLogResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling logs.');
        }

        if (requestParameters.outputId === null || requestParameters.outputId === undefined) {
            throw new runtime.RequiredError('outputId','Required parameter requestParameters.outputId was null or undefined when calling logs.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/outputs/{outputId}/logs`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"outputId"}}`, encodeURIComponent(String(requestParameters.outputId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutputLogResponseFromJSON(jsonValue));
    }

    /**
     * Output logs
     */
    async logs(requestParameters: LogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutputLogResponse> {
        const response = await this.logsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve output
     */
    async retrieveOutputRaw(requestParameters: RetrieveOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Output>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling retrieveOutput.');
        }

        if (requestParameters.outputId === null || requestParameters.outputId === undefined) {
            throw new runtime.RequiredError('outputId','Required parameter requestParameters.outputId was null or undefined when calling retrieveOutput.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/outputs/{outputId}`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"outputId"}}`, encodeURIComponent(String(requestParameters.outputId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutputFromJSON(jsonValue));
    }

    /**
     * Retrieve output
     */
    async retrieveOutput(requestParameters: RetrieveOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Output> {
        const response = await this.retrieveOutputRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve output statistics
     */
    async retrieveOutputStatsRaw(requestParameters: RetrieveOutputStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutputStats>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling retrieveOutputStats.');
        }

        if (requestParameters.outputId === null || requestParameters.outputId === undefined) {
            throw new runtime.RequiredError('outputId','Required parameter requestParameters.outputId was null or undefined when calling retrieveOutputStats.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/outputs/{outputId}/stats`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"outputId"}}`, encodeURIComponent(String(requestParameters.outputId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutputStatsFromJSON(jsonValue));
    }

    /**
     * Retrieve output statistics
     */
    async retrieveOutputStats(requestParameters: RetrieveOutputStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutputStats> {
        const response = await this.retrieveOutputStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Output status
     */
    async statusRaw(requestParameters: StatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutputStatusResponse>> {
        if (requestParameters.collectionId === null || requestParameters.collectionId === undefined) {
            throw new runtime.RequiredError('collectionId','Required parameter requestParameters.collectionId was null or undefined when calling status.');
        }

        if (requestParameters.outputId === null || requestParameters.outputId === undefined) {
            throw new runtime.RequiredError('outputId','Required parameter requestParameters.outputId was null or undefined when calling status.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{collectionId}/outputs/{outputId}/status`.replace(`{${"collectionId"}}`, encodeURIComponent(String(requestParameters.collectionId))).replace(`{${"outputId"}}`, encodeURIComponent(String(requestParameters.outputId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutputStatusResponseFromJSON(jsonValue));
    }

    /**
     * Output status
     */
    async status(requestParameters: StatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutputStatusResponse> {
        const response = await this.statusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update output
     */
    async updateOutputRaw(requestParameters: UpdateOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Output>> {
        if (requestParameters.existingCollectionId === null || requestParameters.existingCollectionId === undefined) {
            throw new runtime.RequiredError('existingCollectionId','Required parameter requestParameters.existingCollectionId was null or undefined when calling updateOutput.');
        }

        if (requestParameters.outputId === null || requestParameters.outputId === undefined) {
            throw new runtime.RequiredError('outputId','Required parameter requestParameters.outputId was null or undefined when calling updateOutput.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling updateOutput.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Token"] = this.configuration.apiKey("X-API-Token"); // APIToken authentication
        }

        const response = await this.request({
            path: `/span/collections/{existingCollectionId}/outputs/{outputId}`.replace(`{${"existingCollectionId"}}`, encodeURIComponent(String(requestParameters.existingCollectionId))).replace(`{${"outputId"}}`, encodeURIComponent(String(requestParameters.outputId))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOutputBodyToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OutputFromJSON(jsonValue));
    }

    /**
     * Update output
     */
    async updateOutput(requestParameters: UpdateOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Output> {
        const response = await this.updateOutputRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
