/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Response object when assigning an image to a collection or collection/device
 * @export
 * @interface AssignTargetImageResponse
 */
export interface AssignTargetImageResponse {
    /**
     * 
     * @type {string}
     * @memberof AssignTargetImageResponse
     */
    collectionId?: string;
    /**
     * 
     * @type {string}
     * @memberof AssignTargetImageResponse
     */
    imageId?: string;
    /**
     * 
     * @type {string}
     * @memberof AssignTargetImageResponse
     */
    deviceId?: string;
}

/**
 * Check if a given object implements the AssignTargetImageResponse interface.
 */
export function instanceOfAssignTargetImageResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssignTargetImageResponseFromJSON(json: any): AssignTargetImageResponse {
    return AssignTargetImageResponseFromJSONTyped(json, false);
}

export function AssignTargetImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignTargetImageResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'collectionId': !exists(json, 'collectionId') ? undefined : json['collectionId'],
        'imageId': !exists(json, 'imageId') ? undefined : json['imageId'],
        'deviceId': !exists(json, 'deviceId') ? undefined : json['deviceId'],
    };
}

export function AssignTargetImageResponseToJSON(value?: AssignTargetImageResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'collectionId': value.collectionId,
        'imageId': value.imageId,
        'deviceId': value.deviceId,
    };
}

