/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.13 interdependent-karson
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoAPMetadata
 */
export interface CoAPMetadata {
    /**
     * 
     * @type {string}
     * @memberof CoAPMetadata
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof CoAPMetadata
     */
    path?: string;
}

export function CoAPMetadataFromJSON(json: any): CoAPMetadata {
    return CoAPMetadataFromJSONTyped(json, false);
}

export function CoAPMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoAPMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'path': !exists(json, 'path') ? undefined : json['path'],
    };
}

export function CoAPMetadataToJSON(value?: CoAPMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'path': value.path,
    };
}


