/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.0 convulsive-launa
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OutputConfig } from './OutputConfig';
import {
    OutputConfigFromJSON,
    OutputConfigFromJSONTyped,
    OutputConfigToJSON,
} from './OutputConfig';
import type { OutputType } from './OutputType';
import {
    OutputTypeFromJSON,
    OutputTypeFromJSONTyped,
    OutputTypeToJSON,
} from './OutputType';

/**
 * Request type when creating new outputs
 * @export
 * @interface CreateOutputBody
 */
export interface CreateOutputBody {
    /**
     * 
     * @type {OutputType}
     * @memberof CreateOutputBody
     */
    type?: OutputType;
    /**
     * 
     * @type {OutputConfig}
     * @memberof CreateOutputBody
     */
    config?: OutputConfig;
    /**
     * 
     * @type {boolean}
     * @memberof CreateOutputBody
     */
    enabled?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateOutputBody
     */
    tags?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateOutputBody interface.
 */
export function instanceOfCreateOutputBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateOutputBodyFromJSON(json: any): CreateOutputBody {
    return CreateOutputBodyFromJSONTyped(json, false);
}

export function CreateOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOutputBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : OutputTypeFromJSON(json['type']),
        'config': !exists(json, 'config') ? undefined : OutputConfigFromJSON(json['config']),
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function CreateOutputBodyToJSON(value?: CreateOutputBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': OutputTypeToJSON(value.type),
        'config': OutputConfigToJSON(value.config),
        'enabled': value.enabled,
        'tags': value.tags,
    };
}

