/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Create a new firmware image
 * @export
 * @interface CreateFirmwareBody
 */
export interface CreateFirmwareBody {
    /**
     * 
     * @type {string}
     * @memberof CreateFirmwareBody
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFirmwareBody
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFirmwareBody
     */
    filename?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateFirmwareBody
     */
    tags?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateFirmwareBody interface.
 */
export function instanceOfCreateFirmwareBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateFirmwareBodyFromJSON(json: any): CreateFirmwareBody {
    return CreateFirmwareBodyFromJSONTyped(json, false);
}

export function CreateFirmwareBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFirmwareBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': !exists(json, 'image') ? undefined : json['image'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'filename': !exists(json, 'filename') ? undefined : json['filename'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function CreateFirmwareBodyToJSON(value?: CreateFirmwareBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
        'version': value.version,
        'filename': value.filename,
        'tags': value.tags,
    };
}

