/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DeviceConfig,
    DeviceConfigFromJSON,
    DeviceConfigFromJSONTyped,
    DeviceConfigToJSON,
    DeviceMetadata,
    DeviceMetadataFromJSON,
    DeviceMetadataFromJSONTyped,
    DeviceMetadataToJSON,
    FirmwareMetadata,
    FirmwareMetadataFromJSON,
    FirmwareMetadataFromJSONTyped,
    FirmwareMetadataToJSON,
    NetworkMetadata,
    NetworkMetadataFromJSON,
    NetworkMetadataFromJSONTyped,
    NetworkMetadataToJSON,
} from './';

/**
 * Request object to create new devices
 * @export
 * @interface CreateDeviceRequest
 */
export interface CreateDeviceRequest {
    /**
     * Tags are metadata for the device that you can set. These are just
     * strings.
     * @type {{ [key: string]: string; }}
     * @memberof CreateDeviceRequest
     */
    tags?: { [key: string]: string; };
    /**
     * 
     * @type {FirmwareMetadata}
     * @memberof CreateDeviceRequest
     */
    firmware?: FirmwareMetadata;
    /**
     * 
     * @type {DeviceConfig}
     * @memberof CreateDeviceRequest
     */
    config?: DeviceConfig;
    /**
     * 
     * @type {DeviceMetadata}
     * @memberof CreateDeviceRequest
     */
    metadata?: DeviceMetadata;
    /**
     * The IMSI is the unique ID for the (e|nu|whatever)SIM card on your device.
     * This is the primary identifier for your device on the network.
     * 
     * Deprecated: The IMSI is replaced by CellularIoTMetadata
     * @type {string}
     * @memberof CreateDeviceRequest
     */
    imsi?: string;
    /**
     * The IMEI number is the unique ID for your hardware as seen by the network.
     * Obviously you might have a completely different view on things.
     * 
     * Deprecated: The IMEI is replaced by CellularIoTMetadata
     * @type {string}
     * @memberof CreateDeviceRequest
     */
    imei?: string;
    /**
     * 
     * @type {NetworkMetadata}
     * @memberof CreateDeviceRequest
     */
    network?: NetworkMetadata;
}

export function CreateDeviceRequestFromJSON(json: any): CreateDeviceRequest {
    return CreateDeviceRequestFromJSONTyped(json, false);
}

export function CreateDeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeviceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'firmware': !exists(json, 'firmware') ? undefined : FirmwareMetadataFromJSON(json['firmware']),
        'config': !exists(json, 'config') ? undefined : DeviceConfigFromJSON(json['config']),
        'metadata': !exists(json, 'metadata') ? undefined : DeviceMetadataFromJSON(json['metadata']),
        'imsi': !exists(json, 'imsi') ? undefined : json['imsi'],
        'imei': !exists(json, 'imei') ? undefined : json['imei'],
        'network': !exists(json, 'network') ? undefined : NetworkMetadataFromJSON(json['network']),
    };
}

export function CreateDeviceRequestToJSON(value?: CreateDeviceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags,
        'firmware': FirmwareMetadataToJSON(value.firmware),
        'config': DeviceConfigToJSON(value.config),
        'metadata': DeviceMetadataToJSON(value.metadata),
        'imsi': value.imsi,
        'imei': value.imei,
        'network': NetworkMetadataToJSON(value.network),
    };
}


