/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.2 subversive-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GatewayConfig } from './GatewayConfig';
import {
    GatewayConfigFromJSON,
    GatewayConfigFromJSONTyped,
    GatewayConfigToJSON,
} from './GatewayConfig';
import type { GatewayType } from './GatewayType';
import {
    GatewayTypeFromJSON,
    GatewayTypeFromJSONTyped,
    GatewayTypeToJSON,
} from './GatewayType';

/**
 * 
 * @export
 * @interface CreateGatewayBody
 */
export interface CreateGatewayBody {
    /**
     * 
     * @type {string}
     * @memberof CreateGatewayBody
     */
    name?: string;
    /**
     * 
     * @type {GatewayType}
     * @memberof CreateGatewayBody
     */
    type?: GatewayType;
    /**
     * 
     * @type {GatewayConfig}
     * @memberof CreateGatewayBody
     */
    config?: GatewayConfig;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CreateGatewayBody
     */
    tags?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateGatewayBody interface.
 */
export function instanceOfCreateGatewayBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateGatewayBodyFromJSON(json: any): CreateGatewayBody {
    return CreateGatewayBodyFromJSONTyped(json, false);
}

export function CreateGatewayBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGatewayBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : GatewayTypeFromJSON(json['type']),
        'config': !exists(json, 'config') ? undefined : GatewayConfigFromJSON(json['config']),
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function CreateGatewayBodyToJSON(value?: CreateGatewayBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': GatewayTypeToJSON(value.type),
        'config': GatewayConfigToJSON(value.config),
        'tags': value.tags,
    };
}

