/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.7 only-deshaun
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FirmwareMetadata,
    FirmwareMetadataFromJSON,
    FirmwareMetadataFromJSONTyped,
    FirmwareMetadataToJSON,
    NetworkMetadata,
    NetworkMetadataFromJSON,
    NetworkMetadataFromJSONTyped,
    NetworkMetadataToJSON,
} from './';

/**
 * 
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * The device ID is assigned by the backend.
     * @type {string}
     * @memberof Device
     */
    deviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    collectionId?: string;
    /**
     * The IMSI is the unique ID for the (e|nu|whatever)SIM card on your device.
     * This is the primary identifier for your device on the network.
     * @type {string}
     * @memberof Device
     */
    imsi?: string;
    /**
     * The IMEI number is the unique ID for your hardware as seen by the network.
     * Obviously you might have a completely different view on things.
     * @type {string}
     * @memberof Device
     */
    imei?: string;
    /**
     * Tags are metadata for the device that you can set. These are just
     * strings.
     * @type {{ [key: string]: string; }}
     * @memberof Device
     */
    tags?: { [key: string]: string; };
    /**
     * 
     * @type {NetworkMetadata}
     * @memberof Device
     */
    network?: NetworkMetadata;
    /**
     * 
     * @type {FirmwareMetadata}
     * @memberof Device
     */
    firmware?: FirmwareMetadata;
}

export function DeviceFromJSON(json: any): Device {
    return DeviceFromJSONTyped(json, false);
}

export function DeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Device {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deviceId': !exists(json, 'deviceId') ? undefined : json['deviceId'],
        'collectionId': !exists(json, 'collectionId') ? undefined : json['collectionId'],
        'imsi': !exists(json, 'imsi') ? undefined : json['imsi'],
        'imei': !exists(json, 'imei') ? undefined : json['imei'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'network': !exists(json, 'network') ? undefined : NetworkMetadataFromJSON(json['network']),
        'firmware': !exists(json, 'firmware') ? undefined : FirmwareMetadataFromJSON(json['firmware']),
    };
}

export function DeviceToJSON(value?: Device | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deviceId': value.deviceId,
        'collectionId': value.collectionId,
        'imsi': value.imsi,
        'imei': value.imei,
        'tags': value.tags,
        'network': NetworkMetadataToJSON(value.network),
        'firmware': FirmwareMetadataToJSON(value.firmware),
    };
}


