/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CertificateInfo,
    CertificateInfoFromJSON,
    CertificateInfoFromJSONTyped,
    CertificateInfoToJSON,
} from './';

/**
 * Response object for certificate info resource
 * @export
 * @interface DeviceCertificateResponse
 */
export interface DeviceCertificateResponse {
    /**
     * 
     * @type {Array<CertificateInfo>}
     * @memberof DeviceCertificateResponse
     */
    certificates?: Array<CertificateInfo>;
}

export function DeviceCertificateResponseFromJSON(json: any): DeviceCertificateResponse {
    return DeviceCertificateResponseFromJSONTyped(json, false);
}

export function DeviceCertificateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceCertificateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'certificates': !exists(json, 'certificates') ? undefined : ((json['certificates'] as Array<any>).map(CertificateInfoFromJSON)),
    };
}

export function DeviceCertificateResponseToJSON(value?: DeviceCertificateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'certificates': value.certificates === undefined ? undefined : ((value.certificates as Array<any>).map(CertificateInfoToJSON)),
    };
}


