/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.7.0 actionable-aryanna
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Statistics for a single firmware image
 * @export
 * @interface FirmwareStats
 */
export interface FirmwareStats {
    /**
     * 
     * @type {number}
     * @memberof FirmwareStats
     */
    firmwareImageSize?: number;
}

/**
 * Check if a given object implements the FirmwareStats interface.
 */
export function instanceOfFirmwareStats(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FirmwareStatsFromJSON(json: any): FirmwareStats {
    return FirmwareStatsFromJSONTyped(json, false);
}

export function FirmwareStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FirmwareStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firmwareImageSize': !exists(json, 'firmwareImageSize') ? undefined : json['firmwareImageSize'],
    };
}

export function FirmwareStatsToJSON(value?: FirmwareStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firmwareImageSize': value.firmwareImageSize,
    };
}

