/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.9.5 spattered-kelvin
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * This is statistics for a single gateway
 * @export
 * @interface GatewayStats
 */
export interface GatewayStats {
    /**
     * 
     * @type {string}
     * @memberof GatewayStats
     */
    messagesUpstream?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayStats
     */
    messagesDownstream?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayStats
     */
    bytesUpstream?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayStats
     */
    bytesDownstream?: string;
}

/**
 * Check if a given object implements the GatewayStats interface.
 */
export function instanceOfGatewayStats(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GatewayStatsFromJSON(json: any): GatewayStats {
    return GatewayStatsFromJSONTyped(json, false);
}

export function GatewayStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'messagesUpstream': !exists(json, 'messagesUpstream') ? undefined : json['messagesUpstream'],
        'messagesDownstream': !exists(json, 'messagesDownstream') ? undefined : json['messagesDownstream'],
        'bytesUpstream': !exists(json, 'bytesUpstream') ? undefined : json['bytesUpstream'],
        'bytesDownstream': !exists(json, 'bytesDownstream') ? undefined : json['bytesDownstream'],
    };
}

export function GatewayStatsToJSON(value?: GatewayStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'messagesUpstream': value.messagesUpstream,
        'messagesDownstream': value.messagesDownstream,
        'bytesUpstream': value.bytesUpstream,
        'bytesDownstream': value.bytesDownstream,
    };
}

