/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.4 pettish-alleen
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GatewayStatus = {
    Unknown: 'unknown',
    Offline: 'offline',
    Online: 'online'
} as const;
export type GatewayStatus = typeof GatewayStatus[keyof typeof GatewayStatus];


export function GatewayStatusFromJSON(json: any): GatewayStatus {
    return GatewayStatusFromJSONTyped(json, false);
}

export function GatewayStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GatewayStatus {
    return json as GatewayStatus;
}

export function GatewayStatusToJSON(value?: GatewayStatus | null): any {
    return value as any;
}

