/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeviceImageState } from './DeviceImageState';
import {
    DeviceImageStateFromJSON,
    DeviceImageStateFromJSONTyped,
    DeviceImageStateToJSON,
} from './DeviceImageState';

/**
 * Response object when retrieving image state for a single device
 * @export
 * @interface GetImageStateResponse
 */
export interface GetImageStateResponse {
    /**
     * 
     * @type {DeviceImageState}
     * @memberof GetImageStateResponse
     */
    state?: DeviceImageState;
}

/**
 * Check if a given object implements the GetImageStateResponse interface.
 */
export function instanceOfGetImageStateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetImageStateResponseFromJSON(json: any): GetImageStateResponse {
    return GetImageStateResponseFromJSONTyped(json, false);
}

export function GetImageStateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetImageStateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': !exists(json, 'state') ? undefined : DeviceImageStateFromJSON(json['state']),
    };
}

export function GetImageStateResponseToJSON(value?: GetImageStateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': DeviceImageStateToJSON(value.state),
    };
}

