/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.7 only-deshaun
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Network metadata for devices.
 * @export
 * @interface NetworkMetadata
 */
export interface NetworkMetadata {
    /**
     * Allocated IP address.
     * @type {string}
     * @memberof NetworkMetadata
     */
    allocatedIp?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkMetadata
     */
    allocatedAt?: string;
    /**
     * Cell ID for device. This might not be set, depending on the provider in
     * use.
     * @type {string}
     * @memberof NetworkMetadata
     */
    cellId?: string;
}

export function NetworkMetadataFromJSON(json: any): NetworkMetadata {
    return NetworkMetadataFromJSONTyped(json, false);
}

export function NetworkMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'allocatedIp': !exists(json, 'allocatedIp') ? undefined : json['allocatedIp'],
        'allocatedAt': !exists(json, 'allocatedAt') ? undefined : json['allocatedAt'],
        'cellId': !exists(json, 'cellId') ? undefined : json['cellId'],
    };
}

export function NetworkMetadataToJSON(value?: NetworkMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'allocatedIp': value.allocatedIp,
        'allocatedAt': value.allocatedAt,
        'cellId': value.cellId,
    };
}


