/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.1 humorous-jaron
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Statistics for a single data router
 * @export
 * @interface OutputStats
 */
export interface OutputStats {
    /**
     * 
     * @type {number}
     * @memberof OutputStats
     */
    forwardErrors?: number;
    /**
     * 
     * @type {string}
     * @memberof OutputStats
     */
    messagesForwarded?: string;
    /**
     * 
     * @type {string}
     * @memberof OutputStats
     */
    bytesForwarded?: string;
}

/**
 * Check if a given object implements the OutputStats interface.
 */
export function instanceOfOutputStats(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OutputStatsFromJSON(json: any): OutputStats {
    return OutputStatsFromJSONTyped(json, false);
}

export function OutputStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'forwardErrors': !exists(json, 'forwardErrors') ? undefined : json['forwardErrors'],
        'messagesForwarded': !exists(json, 'messagesForwarded') ? undefined : json['messagesForwarded'],
        'bytesForwarded': !exists(json, 'bytesForwarded') ? undefined : json['bytesForwarded'],
    };
}

export function OutputStatsToJSON(value?: OutputStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'forwardErrors': value.forwardErrors,
        'messagesForwarded': value.messagesForwarded,
        'bytesForwarded': value.bytesForwarded,
    };
}

