/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.4 pettish-alleen
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CollectionFirmware } from './CollectionFirmware';
import {
    CollectionFirmwareFromJSON,
    CollectionFirmwareFromJSONTyped,
    CollectionFirmwareToJSON,
} from './CollectionFirmware';

/**
 * Request object when updating a collection
 * @export
 * @interface UpdateCollectionBody
 */
export interface UpdateCollectionBody {
    /**
     * The team ID that owns the collection. This field is required. When you
     * create new collections the default is to use your private team ID.
     * @type {string}
     * @memberof UpdateCollectionBody
     */
    teamId?: string;
    /**
     * 
     * @type {CollectionFirmware}
     * @memberof UpdateCollectionBody
     */
    firmware?: CollectionFirmware;
    /**
     * Tags for the collection. Tags are metadata fields that you can assign to
     * the collection.
     * @type {{ [key: string]: string; }}
     * @memberof UpdateCollectionBody
     */
    tags?: { [key: string]: string; };
    /**
     * Enabled flag for the collection. A collection may be disabled or enabled
     * to save time.
     * @type {boolean}
     * @memberof UpdateCollectionBody
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the UpdateCollectionBody interface.
 */
export function instanceOfUpdateCollectionBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateCollectionBodyFromJSON(json: any): UpdateCollectionBody {
    return UpdateCollectionBodyFromJSONTyped(json, false);
}

export function UpdateCollectionBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCollectionBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamId': !exists(json, 'teamId') ? undefined : json['teamId'],
        'firmware': !exists(json, 'firmware') ? undefined : CollectionFirmwareFromJSON(json['firmware']),
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function UpdateCollectionBodyToJSON(value?: UpdateCollectionBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teamId': value.teamId,
        'firmware': CollectionFirmwareToJSON(value.firmware),
        'tags': value.tags,
        'enabled': value.enabled,
    };
}

