/* tslint:disable */
/* eslint-disable */
/**
 * The Span API
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.3 pitch-dark-elza
 * Contact: dev@lab5e.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Verify a certificate
 * @export
 * @interface VerifyCertificateBody
 */
export interface VerifyCertificateBody {
    /**
     * 
     * @type {string}
     * @memberof VerifyCertificateBody
     */
    gatewayId?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCertificateBody
     */
    deviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCertificateBody
     */
    certificate?: string;
}

/**
 * Check if a given object implements the VerifyCertificateBody interface.
 */
export function instanceOfVerifyCertificateBody(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function VerifyCertificateBodyFromJSON(json: any): VerifyCertificateBody {
    return VerifyCertificateBodyFromJSONTyped(json, false);
}

export function VerifyCertificateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyCertificateBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gatewayId': !exists(json, 'gatewayId') ? undefined : json['gatewayId'],
        'deviceId': !exists(json, 'deviceId') ? undefined : json['deviceId'],
        'certificate': !exists(json, 'certificate') ? undefined : json['certificate'],
    };
}

export function VerifyCertificateBodyToJSON(value?: VerifyCertificateBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gatewayId': value.gatewayId,
        'deviceId': value.deviceId,
        'certificate': value.certificate,
    };
}

